import { chromium } from 'playwright'
const b = await chromium.launch({ executablePath:'/usr/bin/chromium', args:['--use-gl=angle','--use-angle=swiftshader'] })
const p = await b.newPage({ viewport:{width:1600,height:900} })
const errs=[]; p.on('pageerror',e=>errs.push('PAGEERR: '+e.message))
p.on('console',m=>{ if(m.type()==='error') errs.push('CONSOLE: '+m.text().slice(0,160)) })
await p.goto('http://localhost:5183/portfolio/?phase=world',{waitUntil:'networkidle'})
await p.waitForTimeout(4500)
const n = await p.evaluate(()=>document.querySelectorAll('.relic').length)
console.log('relics:', n)
await p.click('.relic', { force:true })
await p.waitForTimeout(2500)
const open = await p.evaluate(()=>{ const w=document.querySelector('.pwin'); return w ? (document.querySelector('.pwin__title')?.textContent || document.querySelector('.pwin__boot')?.textContent?.slice(0,60) || 'open') : 'NOT OPEN' })
console.log('after click:', JSON.stringify(open))
await p.screenshot({path:'.shots/relic.png'})
console.log('errors:', errs.length?errs.slice(0,4).join('\n'):'none')
await b.close()
