import { chromium } from 'playwright'
const b = await chromium.launch({ executablePath:'/usr/bin/chromium', args:['--use-gl=angle','--use-angle=swiftshader','--ignore-gpu-blocklist','--enable-webgl'] })
const p = await b.newPage({ viewport:{width:1600,height:900} })
const errs=[]; p.on('pageerror',e=>errs.push('PAGEERR: '+e.message))
await p.goto('http://localhost:5183/portfolio/?phase=world',{waitUntil:'networkidle'})
await p.waitForTimeout(4200)
await p.evaluate(()=>window.__lenis ? window.__lenis.scrollTo(1260,{immediate:true}) : scrollTo(0,1260))
await p.waitForTimeout(1600)
await p.screenshot({path:'.shots/ct-idle.png'})
const box = await p.evaluate(()=>{const e=document.querySelectorAll('.contact__link')[1];const r=e.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}})
await p.mouse.move(box.x, box.y)
await p.waitForTimeout(500)
await p.screenshot({path:'.shots/ct-hover.png'})
console.log('errors:', errs.length?errs.join('\n'):'none')
await b.close()
